### ISSUE TITLE
java.lang.NoSuchMethodError: 'io.vertx.core.net.NetClient io.vertx.core.impl.VertxInternal.createNetClient(io.vertx.core.net.NetClientOptions, io.vertx.core.impl.CloseFuture)'

### ISSUE THREAD

**Issue by siddjain** [vertx-howtos/hibernate-reactive-howto#5]
Hello,

I tried using the sample code here with MySQL but get this error:

```
java.lang.NoSuchMethodError: 'io.vertx.core.net.NetClient io.vertx.core.impl.VertxInternal.createNetClient(io.vertx.core.net.NetClientOptions, io.vertx.core.impl.CloseFuture)'
	at io.vertx.sqlclient.impl.ConnectionFactoryBase.<init>(ConnectionFactoryBase.java:85)
	at io.vertx.mysqlclient.impl.MySQLConnectionFactory.<init>(MySQLConnectionFactory.java:48)
	at io.vertx.mysqlclient.spi.MySQLDriver.createConnectionFactory(MySQLDriver.java:87)
	at io.vertx.mysqlclient.spi.MySQLDriver.lambda$newPoolImpl$1(MySQLDriver.java:66)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.vertx.mysqlclient.spi.MySQLDriver.newPoolImpl(MySQLDriver.java:66)
	at io.vertx.mysqlclient.spi.MySQLDriver.newPool(MySQLDriver.java:53)
	at io.vertx.mysqlclient.spi.MySQLDriver.newPool(MySQLDriver.java:40)
	at io.vertx.sqlclient.spi.Driver.createPool(Driver.java:70)
	at io.vertx.sqlclient.Pool.pool(Pool.java:85)
	at org.hibernate.reactive.pool.impl.DefaultSqlClientPool.createPool(DefaultSqlClientPool.java:184)
	at org.hibernate.reactive.pool.impl.DefaultSqlClientPool.createPool(DefaultSqlClientPool.java:166)
	at org.hibernate.reactive.pool.impl.DefaultSqlClientPool.start(DefaultSqlClientPool.java:134)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.startService(AbstractServiceRegistryImpl.java:344)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:249)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.reactive.provider.service.ReactiveGenerationTarget.prepare(ReactiveGenerationTarget.java:47)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:124)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:157)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:85)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:335)
	at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:41)
	at org.hibernate.reactive.provider.service.ReactiveSessionFactoryBuilder.build(ReactiveSessionFactoryBuilder.java:52)
	at org.hibernate.reactive.provider.impl.ReactiveEntityManagerFactoryBuilder.build(ReactiveEntityManagerFactoryBuilder.java:63)
	at org.hibernate.reactive.provider.ReactivePersistenceProvider.createEntityManagerFactory(ReactivePersistenceProvider.java:53)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
	at cdao.dpde.MainVerticle.lambda$asyncStart$0(MainVerticle.java:35)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:52)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:112)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:89)
	at io.vertx.mutiny.core.Vertx$2.handle(Vertx.java:695)
	at io.vertx.mutiny.core.Vertx$2.handle(Vertx.java:693)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

My `pom.xml`:

```
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-core</artifactId>
      <version>${mutiny-vertx.version}</version>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-web</artifactId>
      <version>${mutiny-vertx.version}</version>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-mutiny-vertx-mysql-client</artifactId>
      <version>${mutiny-vertx.version}</version>
    </dependency>
    <dependency>
      <groupId>org.hibernate.reactive</groupId>
      <artifactId>hibernate-reactive-core</artifactId>
      <version>${hibernate-reactive-core.version}</version>
    </dependency>
```

dependency tree:

```
% mvn dependency:tree
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 11.6
[INFO] os.detected.version.major: 11
[INFO] os.detected.version.minor: 6
[INFO] os.detected.classifier: osx-x86_64
[INFO]
[INFO] -----------------------< cdao.dpde:vertx-sample >-----------------------
[INFO] Building vertx-sample 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ vertx-sample ---
[INFO] cdao.dpde:vertx-sample:jar:1.0.0-SNAPSHOT
[INFO] +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.24:compile
[INFO] +- com.google.protobuf:protobuf-java:jar:3.21.5:compile
[INFO] +- com.google.protobuf:protobuf-java-util:jar:3.21.5:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.8.9:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.27.0:compile
[INFO] |  +- io.smallrye.reactive:mutiny:jar:1.7.0:compile
[INFO] |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  \- io.smallrye.common:smallrye-common-annotation:jar:1.13.0:compile
[INFO] |  +- io.smallrye.reactive:smallrye-mutiny-vertx-runtime:jar:2.27.0:compile
[INFO] |  +- io.vertx:vertx-core:jar:4.3.4:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.82.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.82.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.82.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.82.Final:compile
[INFO] |  |  \- io.netty:netty-resolver-dns:jar:4.1.82.Final:compile
[INFO] |  |     \- io.netty:netty-codec-dns:jar:4.1.82.Final:compile
[INFO] |  \- io.smallrye.reactive:vertx-mutiny-generator:jar:2.27.0:compile
[INFO] |     \- io.vertx:vertx-codegen:jar:4.3.4:compile
[INFO] +- io.smallrye.reactive:smallrye-mutiny-vertx-web:jar:2.27.0:compile
[INFO] |  +- io.vertx:vertx-web:jar:4.3.4:compile
[INFO] |  |  +- io.vertx:vertx-web-common:jar:4.3.4:compile
[INFO] |  |  +- io.vertx:vertx-auth-common:jar:4.3.4:compile
[INFO] |  |  \- io.vertx:vertx-bridge-common:jar:4.3.4:compile
[INFO] |  +- io.smallrye.reactive:smallrye-mutiny-vertx-web-common:jar:2.27.0:compile
[INFO] |  +- io.smallrye.reactive:smallrye-mutiny-vertx-auth-common:jar:2.27.0:compile
[INFO] |  +- io.smallrye.reactive:smallrye-mutiny-vertx-bridge-common:jar:2.27.0:compile
[INFO] |  \- io.smallrye.reactive:smallrye-mutiny-vertx-uri-template:jar:2.27.0:compile
[INFO] |     \- io.vertx:vertx-uri-template:jar:4.3.4:compile
[INFO] +- io.smallrye.reactive:smallrye-mutiny-vertx-mysql-client:jar:2.27.0:compile
[INFO] |  +- io.vertx:vertx-mysql-client:jar:4.3.4:compile
[INFO] |  \- io.smallrye.reactive:smallrye-mutiny-vertx-sql-client:jar:2.27.0:compile
[INFO] +- org.hibernate.reactive:hibernate-reactive-core:jar:1.1.8.Final:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.6.12.Final:compile
[INFO] |  |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.9:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
[INFO] |  |     +- org.jvnet.staxex:stax-ex:jar:1.8:compile
[INFO] |  |     \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.5.0.Final:compile
[INFO] |  \- io.vertx:vertx-sql-client:jar:4.3.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.13.0:compile
[INFO] \- ch.qos.logback:logback-classic:jar:1.2.6:compile
[INFO]    \- ch.qos.logback:logback-core:jar:1.2.6:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.283 s
[INFO] Finished at: 2022-10-01T15:19:28-07:00
[INFO] ------------------------------------------------------------------------
```

thanks for any help.

**Comment by siddjain** [comment]
I was using 2.27.0 of smallrye-mutiny-vertx-core. Downgrading to 2.26.0 fixed the issue. so its a bug in smallrye-mutiny-vertx-core

**Comment by tsegismont** [comment]
There was an internal method changed in `NetClient` recently. If you upgrade `smallrye-mutiny-vertx-core` you need to make sure Maven resolves the correct version of Vert.x (perhaps Hibernate Reactive brings an older one).
